name: auth-deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: cd auth && docker build . -t auth
      - name: Login to DockerHub
        run: docker login -u 535066 -P ${{ secrets.DOCKER_TOKEN }}
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/auth
