name: orders-deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: cd orders && docker build . -t orders
      - name: Login to DockerHub
        run: docker login -u 535066 -p ${{ secrets.DOCKER_TOKEN }}
      - name: Push the Docker image
        run: docker tag orders 535066/orders && docker push 535066/orders
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment orders-depl
      
