name: payments-deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: cd payments && docker build . -t payments
      - name: Login to DockerHub
        run: docker login -u 535066 -p ${{ secrets.DOCKER_TOKEN }}
      - name: Push the Docker image
        run: docker tag payments 535066/payments && docker push 535066/payments
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment payments-depl
      
